### PR TITLE
Fork ready for merge. All merge conflicts resolved. (Merge to fix network fustercluck.)

### PR DESCRIPTION
**Pull request by AnonymousNix**
The old pull request has been closed. The merge will be to the dev branch instead of the master. Merge dev to master afterwards. There are no real changes from the actual master at this point, But merge it anyway so it shows what actually happened on the network. (The chained merges and manual edits made the network graphs very confusing, so it looks like the dev branch and my fork are still way ahead of the master.)

To do after the merge:
-Change inventory layout to be less minecraft-like
-Redesign behavior handling system
-Move item database to an xml file

### CODE REVIEW

**Comment by AnonymousNix** [comment]
(@Gooseguy) gibe de merge boss. ples. gibe da merge. 
(I can't honestly continue until the network graphs are fixed.)

**Comment by christiancosgrove** [comment]
I'm pretty sure I already merged your fork...

**Comment by christiancosgrove** [comment]
I merged it to master by accident and then updated dev from master.

**Comment by christiancosgrove** [comment]
Also, from now on, can we just work on the main repo? I think you @AnonymousNix have contributor status, so you can make your own branches. 

And I don't think we need to make a separate dev branch. Each new major (or minor) feature should have its own branch (just as you did with the recent update). We should strive to make all non-master code bugfree.

**Comment by christiancosgrove** [comment]
Working on XML file right now.

**Pull request closed without merging**
